### ISSUE TITLE
Error when launching monocular with TUM dataset

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/slam-SD-SLAM#11]
Hi,

I've just installed the tool and I'm trying to run the "freiburg1_desk" example from TUM dataset using monocular and TUM1.yaml. However, I'm getting an error, reproduced below. Any ideas about what could be happening? 

I've renamed the rgb.txt file to files.txt and moved it into the /rgb folder.

diego@EINSTEIN:~/SD-SLAM$ ./Examples/Monocular/monocular Examples/Monocular/TUM1.yaml DIEGO_EJEMPLOS/rgbd_dataset_freiburg1_desk/rgb
[INFO] Sequence has 616 images
[DEBUG] Input sensor was set to Monocular

Camera Parameters: 
- fx: 517.306
- fy: 516.469
- cx: 318.643
- cy: 255.314
- k1: 0.262383
- k2: -0.953104
- k3: 1.16331
- p1: -0.005358
- p2: 0.002628
- fps: 30

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 5
- Scale Factor: 2
- Fast Threshold: 20
[DEBUG] Loop closing activated
[INFO] Reading Frame DIEGO_EJEMPLOS/rgbd_dataset_freiburg1_desk/rgb/#

[ERROR] Failed to load image at: DIEGO_EJEMPLOS/rgbd_dataset_freiburg1_desk/rgb/#
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
monocular: ../../src/xcb_io.c:161: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
Abortado (`core' generado)

Thanx in advance,
Diego.

**Comment by eperdices** [comment]
Hi,

It seems an error reading images from files.txt. This line should be a valid image path:

`DIEGO_EJEMPLOS/rgbd_dataset_freiburg1_desk/rgb/#`

Try to use an absolute path and check your files.txt, you can create it running this command inside rgb folder:

`ls *.png > files.txt`

Regards
