### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by xiaozhi12345678** [JdeRobot/slam-SD-SLAM#23]
Hello, is it a complete project?Does it have paper?Emmm, and I want to know how do you finish loop detection. Thank you very much!

**Comment by jmplaza** [comment]
Hi @xiaozhi12345678 , we have a paper for a previous algorithm (https://www.mdpi.com/1424-8220/19/2/302) and a PhD (https://gsyc.urjc.es/jmplaza/students/phd-eduardo_perdices-2017.pdf, Spanish). We are writing two papers about extending SDSLAM algorithm with IMU on one side, and with RGBD sensor on other side (https://gsyc.urjc.es/jmplaza/students/tfm-slam-sdslam+_rgbd-omar_garrido-2020.pdf, Spanish). We intend to finish the papers by this Fall.

**Comment by xiaozhi12345678** [comment]
I see the project doesn't have DBOW files,   it  doesn't have loop detection and optimization, right?

**Comment by xiaozhi12345678** [comment]
I see the project doesn't have DBOW files, it doesn't have loop detection and optimization, right?
