### ISSUE TITLE
this node should be extended to accept images from ICE drivers and ROS drivers

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/slam-SD-SLAM#5]
not only direct opencv capture. The simplest way to do it is using the Comm library from JdeRobot, which automatically maps to underlying ICE image drivers (like cameraserver) or ROS image drivers (like usbcam or ROS bags files).

The [cameraviewer](https://github.com/JdeRobot/JdeRobot/tree/master/src/tools/cameraview) C++ tool at JdeRobot repository uses Comm too. It can be a reference to solve this issue on slam-SD-SLAM.

**Comment by eperdices** [comment]
It is now able to read RGB images from a ROS topic. In the future, it needs to be extended to read depth images and IMU data.
